// apps/react-app/src/app/login/page.tsx
'use client';

import { useRouter } from 'next/navigation';
import { useState } from 'react';
import {
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Field,
  FieldDescription,
  FieldLabel,
  Input,
} from '@surfnet/curve-react';

export default function LoginPage() {
  const router = useRouter();
  const [pending, setPending] = useState(false);

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setPending(true);
    router.push('/browse-apps');
  }

  return (
    <main className="grid min-h-screen place-items-center bg-muted p-4">
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>SURF Access</CardTitle>
          <CardDescription>Sign in to manage your apps.</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <Field>
              <FieldLabel htmlFor="email">Email</FieldLabel>
              <Input
                id="email"
                type="email"
                autoComplete="username"
                defaultValue="freek.vonk@universiteitleiden.nl"
              />
            </Field>

            <Field>
              <FieldLabel htmlFor="password">Password</FieldLabel>
              <Input
                id="password"
                type="password"
                autoComplete="current-password"
                defaultValue="surf"
              />
            </Field>

            <Button type="submit" className="w-full" disabled={pending}>
              {pending ? 'Signing in…' : 'Sign in'}
            </Button>

            <FieldDescription className="text-center">
              Demo credentials: <code>freek.vonk@universiteitleiden.nl</code> / <code>surf</code>
            </FieldDescription>
          </form>
        </CardContent>
      </Card>
    </main>
  );
}

// apps/angular-app/src/app/login/login.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import {
  HlmButtonImports,
  HlmCardImports,
  HlmFieldImports,
  HlmInputImports,
} from '@surfnet/curve-angular';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  imports: [HlmButtonImports, HlmCardImports, HlmFieldImports, HlmInputImports],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoginComponent {
  private readonly router = inject(Router);

  protected readonly pending = signal(false);

  protected onSubmit(event: Event): void {
    event.preventDefault();
    this.pending.set(true);
    this.router.navigateByUrl('/browse-apps');
  }
}

<main class="grid min-h-screen place-items-center bg-muted p-4">
  <div hlmCard class="w-full max-w-sm">
    <div hlmCardHeader>
      <h2 hlmCardTitle>SURF Access</h2>
      <p hlmCardDescription>Sign in to manage your apps.</p>
    </div>
    <div hlmCardContent>
      <form class="space-y-4" (submit)="onSubmit($event)">
        <div hlmField>
          <label hlmFieldLabel for="email">Email</label>
          <input
            hlmInput
            id="email"
            name="email"
            type="email"
            autocomplete="username"
            value="freek.vonk@universiteitleiden.nl"
          />
        </div>
        <div hlmField>
          <label hlmFieldLabel for="password">Password</label>
          <input
            hlmInput
            id="password"
            name="password"
            type="password"
            autocomplete="current-password"
            value="surf"
          />
        </div>
        <button hlmBtn type="submit" class="w-full" [disabled]="pending()">
          {{ pending() ? 'Signing in…' : 'Sign in' }}
        </button>
        <p hlmFieldDescription class="text-center">
          Demo credentials: <code>freek.vonk@universiteitleiden.nl</code> / <code>surf</code>
        </p>
      </form>
    </div>
  </div>
</main>
