// apps/react-app/src/app/browse-apps/page.tsx
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
  Button,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@surfnet/curve-react';
import { getApps, parseCategory, parsePage } from '@/lib/apps';
import { buildHref } from '@/lib/url';

import { AppsSearch } from '@/components/browse-apps/apps-search';
import { CategoryFilter } from '@/components/browse-apps/category-filter';
import { LoadMore } from '@/components/browse-apps/load-more';
import { RowActions } from '@/components/browse-apps/row-actions';
import {
  RowCheckbox,
  SelectAllCheckbox,
  SelectionProvider,
} from '@/components/browse-apps/selection';

const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });

type SearchParams = Promise<{ search?: string; category?: string; page?: string }>;

export default async function BrowseAppsPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const search = params.search ?? '';
  const category = parseCategory(params.category);
  const page = parsePage(params.page);

  const { items, total, hasMore } = await getApps({ search, category, page });
  const ids = items.map((app) => app.id);

  // Build the "load more" href from the current query, bumping the page.
  const nextHref = buildHref('/browse-apps', params, { page: page + 1 });

  return (
    <div className="mx-auto w-full max-w-6xl px-8 py-6">
      <Breadcrumb className="mb-6">
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="#">Home</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbLink href="#">Settings</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage>Profile details</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>

      <div className="mb-8 space-y-1">
        <h1 className="text-3xl font-semibold tracking-tight">Browse apps</h1>
        <p className="text-muted-foreground">
          Manage access to the apps that the Dummy IdP is connected to.
        </p>
      </div>

      <div className="mb-4 flex items-center justify-between gap-4">
        <AppsSearch defaultValue={search} />
        <div className="flex items-center gap-2">
          <CategoryFilter value={category} />
          <Button>Create new application</Button>
        </div>
      </div>

      <SelectionProvider>
        <div className="overflow-hidden rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-10">
                  <SelectAllCheckbox ids={ids} />
                </TableHead>
                <TableHead>App</TableHead>
                <TableHead>Vendor</TableHead>
                <TableHead>Revenue</TableHead>
                <TableHead className="w-10" />
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={5} className="h-24 text-center text-muted-foreground">
                    No apps found.
                  </TableCell>
                </TableRow>
              ) : (
                items.map((app) => (
                  <TableRow key={app.id}>
                    <TableCell>
                      <RowCheckbox id={app.id} label={app.name} />
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-3">
                        <Avatar size="sm">
                          <AvatarImage src={app.iconUrl} alt="" />
                          <AvatarFallback>{app.name.slice(0, 2).toUpperCase()}</AvatarFallback>
                        </Avatar>
                        <span className="font-medium">{app.name}</span>
                      </div>
                    </TableCell>
                    <TableCell className="text-muted-foreground">{app.vendor}</TableCell>
                    <TableCell>{currency.format(app.revenue)}</TableCell>
                    <TableCell>
                      <RowActions appName={app.name} />
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </SelectionProvider>

      <div className="mt-4 flex items-center justify-between">
        {hasMore ? (
          <LoadMore href={nextHref} />
        ) : (
          <span className="text-sm text-muted-foreground">No more apps.</span>
        )}
        <span className="text-sm text-muted-foreground">
          Showing {items.length} of {total}
        </span>
      </div>
    </div>
  );
}

// apps/angular-app/src/app/browse-apps/browse-apps.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { phosphorImage, phosphorPlus } from '@ng-icons/phosphor-icons/regular';
import {
  HlmAvatarImports,
  HlmBreadcrumbImports,
  HlmButtonImports,
  HlmCheckboxImports,
  HlmTableImports,
} from '@surfnet/curve-angular';
import { getApps, parseCategory, parsePage } from '../lib/apps';
import type { AppCategoryFilter, AppRecord } from '../lib/mock-data';
import { AppsSearchComponent } from './apps-search.component';
import { CategoryFilterComponent } from './category-filter.component';
import { RowActionsComponent } from './row-actions.component';

const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });

@Component({
  selector: 'app-browse-apps',
  templateUrl: './browse-apps.component.html',
  imports: [
    AppsSearchComponent,
    CategoryFilterComponent,
    RowActionsComponent,
    HlmAvatarImports,
    HlmBreadcrumbImports,
    HlmButtonImports,
    HlmCheckboxImports,
    HlmTableImports,
    NgIcon,
    RouterLink,
  ],
  providers: [provideIcons({ phosphorImage, phosphorPlus })],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BrowseAppsComponent {
  private readonly router = inject(Router);

  public readonly search = input<string | undefined>('');
  public readonly category = input<string | undefined>('');
  public readonly page = input<string | undefined>('');

  protected readonly selected = signal(new Set<string>());

  protected readonly categoryFilter = computed(() => parseCategory(this.category()));

  protected readonly result = computed(() =>
    getApps({
      search: this.search() ?? '',
      category: this.categoryFilter(),
      page: parsePage(this.page()),
    }),
  );

  protected readonly items = computed(() => this.result().items);
  protected readonly total = computed(() => this.result().total);
  protected readonly hasMore = computed(() => this.result().hasMore);
  protected readonly nextPage = computed(() => parsePage(this.page()) + 1);

  protected readonly isAllSelected = computed(() => {
    const items = this.items();
    return items.length > 0 && items.every((app) => this.selected().has(app.id));
  });

  protected readonly isSomeSelected = computed(() => {
    const items = this.items();
    return items.some((app) => this.selected().has(app.id)) && !this.isAllSelected();
  });

  protected formatRevenue(value: number): string {
    return currency.format(value);
  }

  protected isSelected(app: AppRecord): boolean {
    return this.selected().has(app.id);
  }

  protected onSearchChange(value: string): void {
    this.router.navigate([], {
      queryParams: { search: value || null, page: null },
      queryParamsHandling: 'merge',
    });
  }

  protected onCategoryChange(value: AppCategoryFilter): void {
    this.router.navigate([], {
      queryParams: { category: value === 'All' ? null : value, page: null },
      queryParamsHandling: 'merge',
    });
  }

  protected toggleAll(checked: boolean): void {
    const next = new Set(this.selected());
    for (const app of this.items()) {
      if (checked) {
        next.add(app.id);
      } else {
        next.delete(app.id);
      }
    }
    this.selected.set(next);
  }

  protected toggleRow(app: AppRecord, checked: boolean): void {
    const next = new Set(this.selected());
    if (checked) {
      next.add(app.id);
    } else {
      next.delete(app.id);
    }
    this.selected.set(next);
  }
}

<div class="mx-auto w-full max-w-6xl px-8 py-6">
  <nav hlmBreadcrumb class="mb-6">
    <ol hlmBreadcrumbList>
      <li hlmBreadcrumbItem>
        <a hlmBreadcrumbLink link="/home">Home</a>
      </li>
      <li hlmBreadcrumbSeparator></li>
      <li hlmBreadcrumbItem>
        <a hlmBreadcrumbLink link="/components">Settings</a>
      </li>
      <li hlmBreadcrumbSeparator></li>
      <li hlmBreadcrumbItem>
        <span hlmBreadcrumbPage>Profile details</span>
      </li>
    </ol>
  </nav>

  <div class="mb-8 space-y-1">
    <h1 class="text-3xl font-semibold tracking-tight">Browse apps</h1>
    <p class="text-muted-foreground">
      Manage access to the apps that the Dummy IdP is connected to.
    </p>
  </div>

  <div class="mb-4 flex items-center justify-between gap-4">
    <app-apps-search [search]="search() ?? ''" (searchChange)="onSearchChange($event)" />
    <div class="flex items-center gap-2">
      <app-category-filter
        [category]="categoryFilter()"
        (categoryChange)="onCategoryChange($event)"
      />
      <button hlmBtn variant="outline">
        <ng-icon name="phosphorPlus" />
        Create new application
      </button>
    </div>
  </div>

  <div class="overflow-hidden rounded-md border">
    <div hlmTableContainer>
      <table hlmTable>
        <thead hlmTableHeader>
          <tr hlmTableRow>
            <th hlmTableHead class="w-10">
              <hlm-checkbox
                aria-label="Select all"
                [checked]="isAllSelected()"
                [indeterminate]="isSomeSelected()"
                (checkedChange)="toggleAll($event)"
              />
            </th>
            <th hlmTableHead>App</th>
            <th hlmTableHead>Vendor</th>
            <th hlmTableHead>Revenue</th>
            <th hlmTableHead class="w-10"></th>
          </tr>
        </thead>
        <tbody hlmTableBody>
          @for (app of items(); track app.id) {
          <tr hlmTableRow>
            <td hlmTableCell>
              <hlm-checkbox
                aria-label="Select row"
                [checked]="isSelected(app)"
                (checkedChange)="toggleRow(app, $event)"
              />
            </td>
            <td hlmTableCell>
              <div class="flex items-center gap-3">
                <hlm-avatar>
                  <img hlmAvatarImage [src]="app.iconUrl" alt="" />
                  <span hlmAvatarFallback>
                    <ng-icon name="phosphorImage" />
                  </span>
                </hlm-avatar>
                <span class="font-medium">{{ app.name }}</span>
              </div>
            </td>
            <td hlmTableCell class="text-muted-foreground">{{ app.vendor }}</td>
            <td hlmTableCell>{{ formatRevenue(app.revenue) }}</td>
            <td hlmTableCell>
              <app-row-actions [appName]="app.name" />
            </td>
          </tr>
          } @empty {
          <tr hlmTableRow>
            <td hlmTableCell colspan="5" class="h-24 text-center text-muted-foreground">
              No apps found.
            </td>
          </tr>
          }
        </tbody>
      </table>
    </div>
  </div>

  <div class="mt-4 flex items-center justify-between">
    @if (hasMore()) {
    <a
      hlmBtn
      variant="outline"
      [routerLink]="[]"
      [queryParams]="{ page: nextPage() }"
      queryParamsHandling="merge"
    >
      Load more apps…
    </a>
    } @else {
    <span class="text-sm text-muted-foreground">No more apps.</span>
    }

    <span class="text-sm text-muted-foreground">Showing {{ items().length }} of {{ total() }}</span>
  </div>
</div>
