// apps/angular-app/src/app/shell/app-shell.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HlmSidebarImports } from '@surfnet/curve-angular';
import { AppSidebarComponent } from './app-sidebar.component';

@Component({
  selector: 'app-shell',
  templateUrl: './app-shell.component.html',
  imports: [AppSidebarComponent, HlmSidebarImports, RouterOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppShellComponent {}

<div hlmSidebarWrapper class="min-h-screen w-full">
  <app-sidebar />
  <main hlmSidebarInset>
    <header class="flex h-12 shrink-0 items-center gap-2 border-b px-4 md:hidden">
      <button hlmSidebarTrigger></button>
      <span class="text-sm font-medium">SURF Access</span>
    </header>
    <router-outlet />
  </main>
</div>

// apps/react-app/src/components/app-shell.tsx
'use client';

import type { ReactNode } from 'react';
import { SidebarInset, SidebarProvider, SidebarTrigger } from '@surfnet/curve-react';

import { AppSidebar } from '@/components/app-sidebar';
import type { SessionUser } from '@/lib/mock-data';

/**
 * Client shell for the app area. Holds everything that pulls in `@surfnet/curve-react`
 * (a client-only bundle), so the surrounding layout can stay a Server Component.
 */
export function AppShell({ user, children }: { user: SessionUser; children: ReactNode }) {
  return (
    <SidebarProvider>
      <AppSidebar user={user} />
      <SidebarInset>
        <header className="flex h-12 shrink-0 items-center gap-2 border-b px-4 md:hidden">
          <SidebarTrigger />
          <span className="text-sm font-medium">SURF Access</span>
        </header>
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}
