// apps/angular-app/src/app/shell/app-sidebar.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  phosphorCaretUpDown,
  phosphorSignOut,
  phosphorTerminalWindow,
} from '@ng-icons/phosphor-icons/regular';
import {
  HlmAvatarImports,
  HlmDropdownMenuImports,
  HlmSidebarImports,
} from '@surfnet/curve-angular';
import { MOCK_USER } from '../lib/mock-data';

@Component({
  selector: 'app-sidebar',
  templateUrl: './app-sidebar.component.html',
  imports: [
    HlmAvatarImports,
    HlmDropdownMenuImports,
    HlmSidebarImports,
    NgIcon,
    RouterLink,
    RouterLinkActive,
  ],
  providers: [
    provideIcons({
      phosphorCaretUpDown,
      phosphorSignOut,
      phosphorTerminalWindow,
    }),
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppSidebarComponent {
  private readonly router = inject(Router);

  protected readonly user = MOCK_USER;

  protected readonly userInitials = this.user.name
    .split(' ')
    .map((part) => part.charAt(0))
    .join('')
    .toUpperCase();

  protected signOut(): void {
    this.router.navigateByUrl('/login');
  }
}

<hlm-sidebar collapsible="icon">
  <div hlmSidebarHeader>
    <ul hlmSidebarMenu>
      <li hlmSidebarMenuItem>
        <button hlmSidebarMenuButton size="lg">
          <div
            class="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground"
          >
            <ng-icon name="phosphorTerminalWindow" size="16" />
          </div>
          <div class="flex flex-col gap-0.5 leading-none">
            <span class="font-semibold">SURF Access</span>
            <span class="text-xs text-muted-foreground">v1.0.1</span>
          </div>
          <ng-icon name="phosphorCaretUpDown" class="ml-auto" />
        </button>
      </li>
    </ul>
  </div>

  <div hlmSidebarContent>
    <div hlmSidebarGroup>
      <div hlmSidebarGroupContent>
        <ul hlmSidebarMenu>
          <li hlmSidebarMenuItem>
            <button hlmSidebarMenuButton>
              <ng-icon name="phosphorTerminalWindow" />
              <span>Home</span>
            </button>
          </li>
        </ul>
      </div>
    </div>

    <hlm-sidebar-separator />

    <div hlmSidebarGroup>
      <div hlmSidebarGroupContent>
        <ul hlmSidebarMenu>
          <li hlmSidebarMenuItem>
            <button hlmSidebarMenuButton>
              <ng-icon name="phosphorTerminalWindow" />
              <span>Our apps</span>
            </button>
          </li>
          <li hlmSidebarMenuItem>
            <button hlmSidebarMenuButton>
              <ng-icon name="phosphorTerminalWindow" />
              <span>Enabled apps</span>
            </button>
          </li>
          <li hlmSidebarMenuItem>
            <a
              hlmSidebarMenuButton
              routerLink="/browse-apps"
              routerLinkActive
              #browseAppsLink="routerLinkActive"
              [isActive]="browseAppsLink.isActive"
            >
              <ng-icon name="phosphorTerminalWindow" />
              <span>Browse apps</span>
            </a>
          </li>
          <li hlmSidebarMenuItem>
            <button hlmSidebarMenuButton>
              <ng-icon name="phosphorTerminalWindow" />
              <span>Roles</span>
            </button>
          </li>
          <li hlmSidebarMenuItem>
            <button hlmSidebarMenuButton>
              <ng-icon name="phosphorTerminalWindow" />
              <span>Collaborative groups</span>
            </button>
          </li>
        </ul>
      </div>
    </div>

    <hlm-sidebar-separator />

    <div hlmSidebarGroup>
      <div hlmSidebarGroupContent>
        <ul hlmSidebarMenu>
          <li hlmSidebarMenuItem>
            <button hlmSidebarMenuButton>
              <ng-icon name="phosphorTerminalWindow" />
              <span>My organisation</span>
            </button>
          </li>
          <li hlmSidebarMenuItem>
            <button hlmSidebarMenuButton>
              <ng-icon name="phosphorTerminalWindow" />
              <span>Users</span>
            </button>
          </li>
          <li hlmSidebarMenuItem>
            <button hlmSidebarMenuButton>
              <ng-icon name="phosphorTerminalWindow" />
              <span>Policies</span>
            </button>
          </li>
        </ul>
      </div>
    </div>

    <hlm-sidebar-separator />

    <div hlmSidebarGroup>
      <div hlmSidebarGroupContent>
        <ul hlmSidebarMenu>
          <li hlmSidebarMenuItem>
            <button hlmSidebarMenuButton>
              <ng-icon name="phosphorTerminalWindow" />
              <span>SURF Service desk</span>
            </button>
          </li>
          <li hlmSidebarMenuItem>
            <button hlmSidebarMenuButton>
              <ng-icon name="phosphorTerminalWindow" />
              <span>Give us feedback</span>
            </button>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div hlmSidebarFooter>
    <ul hlmSidebarMenu>
      <li hlmSidebarMenuItem>
        <button
          hlmSidebarMenuButton
          size="lg"
          [hlmDropdownMenuTrigger]="userMenu"
          side="top"
          align="start"
        >
          <hlm-avatar size="sm">
            <img hlmAvatarImage [src]="user.avatarUrl" [alt]="user.name" />
            <span hlmAvatarFallback>{{ userInitials }}</span>
          </hlm-avatar>
          <div class="flex flex-col gap-0.5 leading-none">
            <span class="font-semibold">{{ user.name }}</span>
            <span class="text-xs text-muted-foreground">{{ user.organisation }}</span>
          </div>
          <ng-icon name="phosphorCaretUpDown" class="ml-auto" />
        </button>
        <ng-template #userMenu>
          <hlm-dropdown-menu class="w-56">
            <hlm-dropdown-menu-group>
              <hlm-dropdown-menu-label>
                <div class="flex flex-col">
                  <span class="font-medium">{{ user.name }}</span>
                  <span class="text-xs font-normal text-muted-foreground">{{ user.email }}</span>
                </div>
              </hlm-dropdown-menu-label>
            </hlm-dropdown-menu-group>
            <hlm-dropdown-menu-separator />
            <button hlmDropdownMenuItem (triggered)="signOut()">
              <ng-icon name="phosphorSignOut" />
              <span>Sign out</span>
            </button>
          </hlm-dropdown-menu>
        </ng-template>
      </li>
    </ul>
  </div>
</hlm-sidebar>

// apps/react-app/src/components/app-sidebar.tsx
'use client';

import { useRouter } from 'next/navigation';
import { CaretUpDownIcon, SignOutIcon, TerminalWindowIcon } from '@phosphor-icons/react';
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupContent,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarSeparator,
} from '@surfnet/curve-react';

import type { SessionUser } from '@/lib/mock-data';

type NavItem = { title: string; active?: boolean };
type NavGroup = { items: NavItem[] };

const groups: NavGroup[] = [
  {
    items: [{ title: 'Home' }],
  },
  {
    items: [
      { title: 'Our apps' },
      { title: 'Enabled apps' },
      { title: 'Browse apps', active: true },
      { title: 'Roles' },
      { title: 'Collaborative groups' },
    ],
  },
  {
    items: [{ title: 'My organisation' }, { title: 'Users' }, { title: 'Policies' }],
  },
  {
    items: [{ title: 'SURF Service desk' }, { title: 'Give us feedback' }],
  },
];

export function AppSidebar({ user }: { user: SessionUser }) {
  const router = useRouter();

  const initials = user.name
    .split(' ')
    .map((part) => part[0])
    .join('')
    .slice(0, 2)
    .toUpperCase();

  return (
    <Sidebar collapsible="icon">
      <SidebarHeader>
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton size="lg">
              <div className="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
                <TerminalWindowIcon className="size-4" />
              </div>
              <div className="flex flex-col gap-0.5 leading-none">
                <span className="font-semibold">SURF Access</span>
                <span className="text-xs text-muted-foreground">v1.0.1</span>
              </div>
              <CaretUpDownIcon className="ml-auto" />
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarHeader>

      <SidebarContent>
        {groups.flatMap((group, index) => [
          <SidebarGroup key={index}>
            <SidebarGroupContent>
              <SidebarMenu>
                {group.items.map((item) => (
                  <SidebarMenuItem key={item.title}>
                    <SidebarMenuButton isActive={item.active} tooltip={item.title}>
                      <TerminalWindowIcon />
                      <span>{item.title}</span>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>,
          index < groups.length - 1 ? <SidebarSeparator key={`sep-${index}`} /> : null,
        ])}
      </SidebarContent>

      <SidebarFooter>
        <SidebarMenu>
          <SidebarMenuItem>
            <DropdownMenu>
              <DropdownMenuTrigger
                render={
                  <SidebarMenuButton size="lg">
                    <Avatar size="sm">
                      <AvatarImage src={user.avatarUrl} alt={user.name} />
                      <AvatarFallback>{initials}</AvatarFallback>
                    </Avatar>
                    <div className="flex flex-col gap-0.5 leading-none">
                      <span className="font-semibold">{user.name}</span>
                      <span className="text-xs text-muted-foreground">{user.organisation}</span>
                    </div>
                    <CaretUpDownIcon className="ml-auto" />
                  </SidebarMenuButton>
                }
              />
              <DropdownMenuContent side="top" align="start" className="w-56">
                <DropdownMenuGroup>
                  <DropdownMenuLabel>
                    <div className="flex flex-col">
                      <span className="font-medium">{user.name}</span>
                      <span className="text-xs font-normal text-muted-foreground">
                        {user.email}
                      </span>
                    </div>
                  </DropdownMenuLabel>
                </DropdownMenuGroup>
                <DropdownMenuSeparator />
                <DropdownMenuItem onClick={() => router.push('/login')}>
                  <SignOutIcon />
                  Sign out
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarFooter>
    </Sidebar>
  );
}
