// apps/angular-app/src/app/browse-apps/row-actions.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { phosphorDotsThreeBold } from '@ng-icons/phosphor-icons/bold';
import { HlmButtonImports, HlmDropdownMenuImports } from '@surfnet/curve-angular';

@Component({
  selector: 'app-row-actions',
  templateUrl: './row-actions.component.html',
  imports: [HlmButtonImports, HlmDropdownMenuImports, NgIcon],
  providers: [provideIcons({ phosphorDotsThreeBold })],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RowActionsComponent {
  public readonly appName = input.required<string>();

  protected readonly ariaLabel = computed(() => `Actions for ${this.appName()}`);
}

<button
  hlmBtn
  variant="ghost"
  size="icon-sm"
  [attr.aria-label]="ariaLabel()"
  [hlmDropdownMenuTrigger]="menu"
  align="end"
>
  <ng-icon name="phosphorDotsThreeBold" />
</button>

<ng-template #menu>
  <hlm-dropdown-menu>
    <hlm-dropdown-menu-group>
      <hlm-dropdown-menu-label>Actions</hlm-dropdown-menu-label>
      <button hlmDropdownMenuItem>View details</button>
      <button hlmDropdownMenuItem>Manage access</button>
    </hlm-dropdown-menu-group>
    <hlm-dropdown-menu-separator />
    <button hlmDropdownMenuItem variant="destructive">Remove</button>
  </hlm-dropdown-menu>
</ng-template>

// apps/react-app/src/components/browse-apps/row-actions.tsx
'use client';

import { DotsThreeIcon } from '@phosphor-icons/react';
import {
  Button,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@surfnet/curve-react';

export function RowActions({ appName }: { appName: string }) {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        render={
          <Button variant="ghost" size="icon-sm" aria-label={`Actions for ${appName}`}>
            <DotsThreeIcon weight="bold" />
          </Button>
        }
      />
      <DropdownMenuContent align="end">
        <DropdownMenuGroup>
          <DropdownMenuLabel>Actions</DropdownMenuLabel>
          <DropdownMenuItem>View details</DropdownMenuItem>
          <DropdownMenuItem>Manage access</DropdownMenuItem>
        </DropdownMenuGroup>
        <DropdownMenuSeparator />
        <DropdownMenuItem variant="destructive">Remove</DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
